---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: mh-latex-cv.tex
geometry: margin = 0.55in

title: "Resume"
author: Matt Herman
# jobtitle: "Chief Brewer, Arthur Guinness & Son"
address: "39 Huntville Road · Katonah, NY 10536"
fontawesome: yes
email: mfherman@gmail.com
# github: mfherman
phone: "917-374-1939"
web: mattherman.info
updated: yes

# keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
linkcolor: black
urlcolor: black
---

# EDUCATION
**City University of New York, Hunter College** \hfill New York, NY \newline
Master of Science in Applied Social Research \hfill May 2018 

**Columbia University, Columbia College** \hfill New York, NY \newline
Bachelor of Arts in American Studies \hfill May 2006  

# EXPERIENCE
**Council of State Governments Justice Center** \hfill New York, NY  
*Data Scientist, Research Division* \hfill July 2022 -- present  

- Gather and clean criminal justice data from partner agencies and public sources
- Analyze and model data to generate insights using the R programming language
- Build interactive and static data visualizations to communicate results of quantitative analyses
- Collaborate with CSG State Initiatives Division to develop policy recommendations

**NYC Administration for Children’s Services** \hfill New York, NY  
*Deputy Director, ChildStat Data* \hfill March 2020 -- July 2022  
*Senior Analyst, ChildStat Data* \hfill January 2019 -- March 2020  

- Generated outcome measures and performance indicators for child welfare casework from administrative databases
- Developed an automated and reproducible workflow using R and SQL to query databases, aggregate and summarize metrics, and create HTML and PDF dashboards, reports, and presentations
- Collaborated with managers of frontline child protection staff to interpret data in order to create actionable quality improvement plans and assess the impact of these plans
<!-- - Build Covid-19 "Early Alert Dashboard" to track week-to-week changes in child protection metrics -->
<!-- - Create internal R package with functions to support analysis including address geocoding, database connections, common data aggregations, and ggplot2 themes and palettes -->
<!-- - Manage two analysts and support their work product and professional development by conducting frequent code review and teaching R classes -->

**Center for Innovation through Data Intelligence, Office of the Mayor** \hfill New York, NY  
*Research Intern* \hfill June 2017 -- May 2018

- Developed predictive model to identify individuals at risk of becoming homeless using natural language processing and machine learning tools
- Matched individual-level data across multiple NYC administrative databases

<!-- **Mapping the Solidarity Economy Project, Professor Marianna Pavlovskaya** \hfill New York, NY   -->
<!-- *Research Assistant* \hfill February 2018 -- present -->

<!-- - Download, clean, and analyze financial data from the National Credit Union Administration -->
<!-- - Build maps and perform spatial analysis of cooperative businesses -->

<!-- **Ends Meat** \hfill Brooklyn, NY   -->
<!-- *Director of Operations* \hfill March 2015 -- present -->

<!-- - Develop financial, regulatory, and management systems for butcher shop/salumeria -->
<!-- - Create short, medium, and long-term business model and budgets -->

<!-- **Measure of America** \hfill Brooklyn, NY   -->
<!-- *Data Analysis Intern* \hfill Jan 2017 -- June 2017 -->

<!-- - Obtained, cleaned, and analyzed large public datasets including the American Community Survey -->
<!-- - Created maps, graphs, and charts of demographic, economic, and health indicators -->

<!-- **Religion and Society Study** \hfill Lusaka, Zambia   -->
<!-- *Research Coordinator* \hfill June 2016 -- Aug 2016 -->

<!-- -	Built partnerships with and documented political activities of key church groups -->
<!-- -	Conducted interviews with religious and civil society leaders -->
<!-- -	Acquired data from Zambian government agencies related to religious organizations -->

**StoryCorps** \hfill Brooklyn, NY  
*Door-to-Door Facilitator* \hfill Nov 2008 -- Sept 2011  
*Development Associate* \hfill May 2007 -- Nov 2008

- Helped people record the stories of their lives for one of the largest American oral history projects
- Collected, processed, and archived interview materials to be cataloged by the Library of Congress
-	Prepared grant proposals and reports for foundation and government funders

# OPEN SOURCE CONTRIBUTIONS
- Co-author of [**tidycensus**](https://walker-data.com/tidycensus/) R package, making it easy to download US Census and American Community Survey data using the Census web API
- Creator of [**nycgeo**](https://nycgeo.mattherman.info/) R package, containing spatial data files for geographic and administrative boundaries in NYC
- Creator of [**Covid-19 tracking site for Westchester County**](https://westchester-covid.mattherman.info/), including maps, charts, and tables highlighting cases, testing, and fatality trends by county; per capita case counts and trends at the municipal-level; racial disparities in Covid-19 deaths and cases; cases in schools and nursing homes; and hospital capacity

# SKILLS AND TOOLS
Data wrangling, aggregation, and modeling with R and SQL; Visualization and communication with ggplot2, R Markdown, and Plotly; Mapping with Leaflet, Mapbox, and ArcGIS; Collaboration with Git and GitHub