---
title: CV
format:
  quarto-cv-pdf: default
author: Matt Herman
date: last-modified
phone: 917-374-1939
address: "6 First Avenue · Montpelier, VT 05602"
email: mfherman@gmail.com
fontsize: 11pt
#fontfamily: ebgaramond-maths # default font LaTeX package https://tug.org/FontCatalogue/about.html
#mainfont: Ubuntu # if you want to use a different locally installed font
#CJKmainfont: oto Sans CJK JP # locally installed Asian character font, must use with xelatex
#github: github # github account
# orcid: 0000-0002-1825-0097 # orcid identifier
#osf: ymqui # osf five character id
#twitter: twitter # twitter handle
#web: quarto.org
fontawesome: yes
validate-yaml: false
#csl: apa-cv.csl
---

# EDUCATION
**City University of New York, Hunter College** \hfill New York, NY \newline
Master of Science in Applied Social Research \hfill May 2018 

**Columbia University, Columbia College** \hfill New York, NY \newline
Bachelor of Arts in American Studies \hfill May 2006  

# EXPERIENCE
**Council of State Governments Justice Center** \hfill New York, NY  
*Deputy Program Director, Data Science, Research Division* \hfill July 2024 -- present
*Project Manager, Data Science, Research Division* \hfill July 2022 -- June 2024

- Lead development of online courses and learning communities for analysts at state corrections agencies as part of the Advancing Data in Corrections program
- Facilitate criminal justice agency data sharing through the Justice Counts initiative by managing technical relationships with agency staff, leading metric development, and collaborating with Recidiviz on development of a data publishing platform
- Mentor early career data scientists by conducting code reviews, hosting drop-in office hours, and developing internal documentation and guidance
- Supervise two data scientists and oversee their work product and professional development

*Data Scientist, Research Division* \hfill July 2021 -- June 2022  

- Gathered and cleaned criminal justice data from state corrections agencies and public sources as part of the Justice Reinvestment Initiative
- Analyzed and modeled corrections data to generate insights and apply findings to police recommendations
- Built interactive and static data visualizations to communicate results of quantitative analyses for technical and non-technical audiences

**NYC Administration for Children’s Services** \hfill New York, NY  
*Deputy Director, ChildStat Data* \hfill March 2020 -- July 2021  
*Senior Analyst, ChildStat Data* \hfill January 2019 -- March 2020  

- Generated outcome measures and performance indicators for child welfare casework from administrative databases
- Developed an automated and reproducible workflow using R and SQL to query databases, aggregate and summarize metrics, and create HTML and PDF dashboards, reports, and presentations
- Collaborated with managers of frontline child protection staff to interpret data in order to create actionable quality improvement plans and assess the impact of these plans
- Supervised two analysts and oversaw their work product and professional development

**Center for Innovation through Data Intelligence, Office of the Mayor** \hfill New York, NY  
*Research Intern* \hfill June 2017 -- May 2018

- Developed predictive model to identify individuals at risk of becoming homeless using natural language processing and machine learning tools
- Matched individual-level data across multiple NYC administrative databases

**StoryCorps** \hfill Brooklyn, NY  
*Door-to-Door Facilitator* \hfill Nov 2008 -- Sept 2011  
*Development Associate* \hfill May 2007 -- Nov 2008

- Helped people record the stories of their lives for one of the largest American oral history projects
- Collected, processed, and archived interview materials to be cataloged by the Library of Congress
-	Prepared grant proposals and reports for foundation and government funders

# OPEN SOURCE CONTRIBUTIONS
- Co-author of [**tidycensus**](https://walker-data.com/tidycensus/) R package, making it easy to download US Census and American Community Survey data using the Census web API
- Creator of [**nycgeo**](https://nycgeo.mattherman.info/) R package, containing spatial data files for geographic and administrative boundaries in NYC
- Creator of [**Covid-19 tracking site for Westchester County**](https://westchester-covid.mattherman.info/), including maps, charts, and tables highlighting cases, testing, and fatality trends by county; per capita case counts and trends at the municipal-level; racial disparities in Covid-19 deaths and cases; cases in schools and nursing homes; and hospital capacity

# SKILLS AND TOOLS
Data wrangling, aggregation, and modeling with R and SQL; Visualization and communication with ggplot2, Quarto, and Plotly; Mapping with Leaflet, Mapbox, and ArcGIS; Collaboration with Git and GitHub